include(CMakeFindDependencyMacro)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
find_dependency(MUMPS)
find_dependency(ARPACK)
find_dependency(Eigen3)
include("${CMAKE_CURRENT_LIST_DIR}/CheckBoost.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/NuToTargets.cmake")
